//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class absences
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dateab { get; set; }
        public string motif { get; set; }
        public Nullable<int> idPolicier { get; set; }
        public Nullable<System.DateTime> datef { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> dateS { get; set; }
    
        public virtual Policier Policier { get; set; }
    }
}
