//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class conge
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dateD { get; set; }
        public Nullable<System.DateTime> dateF { get; set; }
        public Nullable<int> typeConge { get; set; }
        public Nullable<int> idPolicier { get; set; }
        public Nullable<System.DateTime> dateSave { get; set; }
    
        public virtual Policier Policier { get; set; }
        public virtual Type_Conge Type_Conge { get; set; }
    }
}
