//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epouses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Epouses()
        {
            this.Enfants = new HashSet<Enfants>();
        }
    
        public int Epouse_ID { get; set; }
        public string Nom_epouse { get; set; }
        public Nullable<System.DateTime> Date_mariage { get; set; }
        public Nullable<System.DateTime> Date_divorce { get; set; }
        public string Statut { get; set; }
        public Nullable<int> idPolicier { get; set; }
        public Nullable<int> nbrenfant { get; set; }
        public Nullable<System.DateTime> DateN { get; set; }
        public string Lieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enfants> Enfants { get; set; }
        public virtual Policier Policier { get; set; }
    }
}
