//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class formation
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dateD { get; set; }
        public Nullable<System.DateTime> dateF { get; set; }
        public Nullable<int> typeFormation { get; set; }
        public string numdec { get; set; }
        public Nullable<System.DateTime> datedec { get; set; }
        public string autorite { get; set; }
        public Nullable<int> idpolicier { get; set; }
    
        public virtual Policier Policier { get; set; }
        public virtual Type_Formation Type_Formation { get; set; }
    }
}
