//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBpoliceEntities : DbContext
    {
        public DBpoliceEntities()
            : base("name=DBpoliceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<absences> absences { get; set; }
        public virtual DbSet<adress> adress { get; set; }
        public virtual DbSet<Affectation> affectation { get; set; }
        public virtual DbSet<agence> agence { get; set; }
        public virtual DbSet<conge> conge { get; set; }
        public virtual DbSet<congeMaladie> congeMaladie { get; set; }
        public virtual DbSet<decede> decede { get; set; }
        public virtual DbSet<decision> decision { get; set; }
        public virtual DbSet<detach_agence> detach_agence { get; set; }
        public virtual DbSet<Direction> Direction { get; set; }
        public virtual DbSet<divers> divers { get; set; }
        public virtual DbSet<Enfants> Enfants { get; set; }
        public virtual DbSet<Epouses> Epouses { get; set; }
        public virtual DbSet<etatCivil> etatCivil { get; set; }
        public virtual DbSet<etude> etude { get; set; }
        public virtual DbSet<ficheSolde> ficheSolde { get; set; }
        public virtual DbSet<filesImages> filesImages { get; set; }
        public virtual DbSet<fonction> fonction { get; set; }
        public virtual DbSet<formation> formation { get; set; }
        public virtual DbSet<Grad> Grad { get; set; }
        public virtual DbSet<instruction> instruction { get; set; }
        public virtual DbSet<lien_parenté> lien_parenté { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<mutation> mutation { get; set; }
        public virtual DbSet<notation> notation { get; set; }
        public virtual DbSet<officier> officier { get; set; }
        public virtual DbSet<Policier> Policier { get; set; }
        public virtual DbSet<presences> presences { get; set; }
        public virtual DbSet<punition> punition { get; set; }
        public virtual DbSet<recompense> recompense { get; set; }
        public virtual DbSet<sanction> sanction { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<sous_direction> sous_direction { get; set; }
        public virtual DbSet<Statut> Statut { get; set; }
        public virtual DbSet<tblLieuNaiss> tblLieuNaiss { get; set; }
        public virtual DbSet<typ_doc> typ_doc { get; set; }
        public virtual DbSet<Type_Conge> Type_Conge { get; set; }
        public virtual DbSet<type_dec> type_dec { get; set; }
        public virtual DbSet<type_decision> type_decision { get; set; }
        public virtual DbSet<Type_Formation> Type_Formation { get; set; }
        public virtual DbSet<Type_recompense> Type_recompense { get; set; }
        public virtual DbSet<Type_sanction> Type_sanction { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<logs> logs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<polic> polic { get; set; }
        public virtual DbSet<View_absenc> View_absenc { get; set; }
        public virtual DbSet<View_congé> View_congé { get; set; }
        public virtual DbSet<View_departement> View_departement { get; set; }
        public virtual DbSet<View_direction> View_direction { get; set; }
        public virtual DbSet<View_enfant> View_enfant { get; set; }
        public virtual DbSet<View_formation> View_formation { get; set; }
        public virtual DbSet<View_grade> View_grade { get; set; }
        public virtual DbSet<View_image> View_image { get; set; }
        public virtual DbSet<View_MUT> View_MUT { get; set; }
        public virtual DbSet<View_policDir> View_policDir { get; set; }
        public virtual DbSet<View_policierDivorce> View_policierDivorce { get; set; }
        public virtual DbSet<View_policierGrad> View_policierGrad { get; set; }
        public virtual DbSet<View_presence> View_presence { get; set; }
        public virtual DbSet<View_recompense> View_recompense { get; set; }
        public virtual DbSet<View_resume> View_resume { get; set; }
        public virtual DbSet<View_sanction> View_sanction { get; set; }
        public virtual DbSet<View_congeAnn> View_congeAnn { get; set; }
        public virtual DbSet<View_congeMal> View_congeMal { get; set; }

        public virtual DbSet<View_punition> View_punition { get; set; }
        public virtual DbSet<Affectation> Affectation { get; set; }
        public virtual DbSet<View_affetc> View_affetc { get; set; }
        public virtual DbSet<congeAnnuel> congeAnnuel { get; set; }
        public virtual DbSet<View_decision> View_decision { get; set; }
    }
}
