//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class polic
    {
        public int Matricule_ID { get; set; }
        public string Nom_policier { get; set; }
        public string Nom_pere { get; set; }
        public string Nom_mere { get; set; }
        public Nullable<System.DateTime> Date_naissance { get; set; }
        public Nullable<int> Adresse_ID { get; set; }
        public Nullable<int> Taille { get; set; }
        public Nullable<int> Poids { get; set; }
        public Nullable<int> statu { get; set; }
        public Nullable<System.DateTime> DateDebut_service { get; set; }
        public Nullable<int> Numero_CNI { get; set; }
        public Nullable<System.DateTime> DateDelivrance_CNI { get; set; }
        public Nullable<int> Numero_CP { get; set; }
        public Nullable<System.DateTime> DateDelivrance_CP { get; set; }
        public Nullable<System.DateTime> DateFin_service { get; set; }
        public string genre { get; set; }
        public Nullable<int> idGrad { get; set; }
        public Nullable<System.DateTime> datedec { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> idfonction { get; set; }
        public Nullable<int> iddirect { get; set; }
        public Nullable<int> nbrepouse { get; set; }
        public Nullable<int> idetude { get; set; }
        public Nullable<int> telephone { get; set; }
        public Nullable<int> idservice { get; set; }
        public Nullable<int> iddetachement { get; set; }
        public string adresse { get; set; }
        public Nullable<int> Idaresse { get; set; }
        public Nullable<int> agence_ID { get; set; }
        public string Libelle { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Expr4 { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> Expr6 { get; set; }
        public Nullable<int> Niveau_ID { get; set; }
        public Nullable<int> Grade_ID { get; set; }
        public string numdec { get; set; }
        public Nullable<int> Direction_ID { get; set; }
        public string Type_direction { get; set; }
        public Nullable<int> Statut_ID { get; set; }
        public string Expr7 { get; set; }
        public Nullable<System.DateTime> daterecru { get; set; }
        public string LieuN { get; set; }
        public Nullable<System.DateTime> dateDAvanc { get; set; }
        public string Affect { get; set; }
        public string Nom_epouse { get; set; }
        public Nullable<int> nbrenfant { get; set; }
        public Nullable<System.DateTime> DateN { get; set; }
        public string Lieu { get; set; }
        public Nullable<int> Epouse_ID { get; set; }
        public Nullable<System.DateTime> Date_mariage { get; set; }
        public Nullable<System.DateTime> Date_divorce { get; set; }
        public string Statut { get; set; }
        public Nullable<int> idPolicier { get; set; }
    }
}
