//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Policier()
        {
            this.absences = new HashSet<absences>();
            this.conge = new HashSet<conge>();
            this.congeMaladie = new HashSet<congeMaladie>();
            this.decision = new HashSet<decision>();
            this.divers = new HashSet<divers>();
            this.Enfants = new HashSet<Enfants>();
            this.Epouses = new HashSet<Epouses>();
            this.etatCivil = new HashSet<etatCivil>();
            this.ficheSolde = new HashSet<ficheSolde>();
            this.filesImages = new HashSet<filesImages>();
            this.formation = new HashSet<formation>();
            this.instruction = new HashSet<instruction>();
            this.mutation = new HashSet<mutation>();
            this.notation = new HashSet<notation>();
            this.presences = new HashSet<presences>();
            this.punition = new HashSet<punition>();
            this.recompense = new HashSet<recompense>();
            this.sanction = new HashSet<sanction>();
            this.Affectation = new HashSet<Affectation>();
            this.congeAnnuel = new HashSet<congeAnnuel>();
        }
    
        public int Matricule_ID { get; set; }
        public string Nom_policier { get; set; }
        public string Nom_pere { get; set; }
        public string Nom_mere { get; set; }
        public Nullable<System.DateTime> Date_naissance { get; set; }
        public Nullable<int> Adresse_ID { get; set; }
        public Nullable<int> Taille { get; set; }
        public Nullable<int> Poids { get; set; }
        public Nullable<int> statu { get; set; }
        public Nullable<System.DateTime> DateDebut_service { get; set; }
        public Nullable<System.DateTime> DateFin_service { get; set; }
        public Nullable<int> Numero_CNI { get; set; }
        public Nullable<System.DateTime> DateDelivrance_CNI { get; set; }
        public Nullable<int> Numero_CP { get; set; }
        public Nullable<System.DateTime> DateDelivrance_CP { get; set; }
        public string genre { get; set; }
        public Nullable<int> idGrad { get; set; }
        public string numdec { get; set; }
        public Nullable<System.DateTime> datedec { get; set; }
        public byte[] photo1 { get; set; }
        public byte[] photo2 { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> idfonction { get; set; }
        public Nullable<int> iddirect { get; set; }
        public Nullable<int> nbrepouse { get; set; }
        public Nullable<int> telephone { get; set; }
        public Nullable<int> idetude { get; set; }
        public Nullable<int> idservice { get; set; }
        public Nullable<int> iddetachement { get; set; }
        public Nullable<int> decede { get; set; }
        public Nullable<System.DateTime> daterecru { get; set; }
        public Nullable<System.DateTime> dateDAvanc { get; set; }
        public string LieuN { get; set; }
        public string Affect { get; set; }
        public Nullable<int> nbrenfant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<absences> absences { get; set; }
        public virtual adress adress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conge> conge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<congeMaladie> congeMaladie { get; set; }
        public virtual decede decede1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<decision> decision { get; set; }
        public virtual detach_agence detach_agence { get; set; }
        public virtual Direction Direction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<divers> divers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enfants> Enfants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Epouses> Epouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<etatCivil> etatCivil { get; set; }
        public virtual etude etude { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ficheSolde> ficheSolde { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filesImages> filesImages { get; set; }
        public virtual fonction fonction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formation> formation { get; set; }
        public virtual Grad Grad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instruction> instruction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mutation> mutation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notation> notation { get; set; }
        public virtual Policier Policier1 { get; set; }
        public virtual Policier Policier2 { get; set; }
        public virtual service service { get; set; }
        public virtual Statut Statut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<presences> presences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<punition> punition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recompense> recompense { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanction> sanction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affectation> Affectation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<congeAnnuel> congeAnnuel { get; set; }
    }
}
