//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanction
    {
        public int id { get; set; }
        public Nullable<System.DateTime> datedec { get; set; }
        public Nullable<int> numdec { get; set; }
        public string motif { get; set; }
        public Nullable<int> typeSanct { get; set; }
        public Nullable<int> idPolicier { get; set; }
        public string autorite { get; set; }
    
        public virtual Policier Policier { get; set; }
        public virtual Type_sanction Type_sanction { get; set; }
    }
}
