//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_resume
    {
        public string Nom_policier { get; set; }
        public string etatCivil { get; set; }
        public Nullable<System.DateTime> Date_naissance { get; set; }
        public string grade { get; set; }
        public Nullable<System.DateTime> daterecru { get; set; }
        public int Matricule_ID { get; set; }
        public Nullable<int> nbrenfant { get; set; }
        public string libelle { get; set; }
        public byte[] photo { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> datedec { get; set; }
    }
}
