//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_policierDivorce
    {
        public int Matricule_ID { get; set; }
        public string Nom_policier { get; set; }
        public int Epouse_ID { get; set; }
        public string Nom_epouse { get; set; }
        public Nullable<System.DateTime> Date_mariage { get; set; }
        public Nullable<System.DateTime> Date_divorce { get; set; }
        public string Statut { get; set; }
        public Nullable<int> nbrenfant { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
