//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_direction
    {
        public int Direction_ID { get; set; }
        public string Type_direction { get; set; }
        public int id { get; set; }
        public string libelle { get; set; }
        public Nullable<int> idDirect { get; set; }
        public int Expr1 { get; set; }
        public string Expr2 { get; set; }
        public Nullable<int> idsouDirect { get; set; }
    }
}
