//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_affetc
    {
        public int Matricule_ID { get; set; }
        public Nullable<System.DateTime> dateA { get; set; }
        public string lieu { get; set; }
        public string comment { get; set; }
        public string numNs { get; set; }
        public byte[] document { get; set; }
    }
}
