//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_absenc
    {
        public string Nom_policier { get; set; }
        public string Nom_pere { get; set; }
        public string Nom_mere { get; set; }
        public Nullable<System.DateTime> dateab { get; set; }
        public string libelle { get; set; }
        public int Matricule_ID { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> datef { get; set; }
        public Nullable<System.DateTime> dateS { get; set; }
    }
}
