//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_punition
    {
        public string libelle { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> datefait { get; set; }
        public int Matricule_ID { get; set; }
        public Nullable<int> id { get; set; }
        public string nomfichier { get; set; }
        public byte[] document { get; set; }
        public string createby { get; set; }
        public Nullable<int> idtype { get; set; }
        public Nullable<int> duree { get; set; }
    }
}

