//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MUT
    {
        public Nullable<int> idPolicier { get; set; }
        public string Libelle { get; set; }
        public string typdeci { get; set; }
        public string motif { get; set; }
        public string numdec { get; set; }
        public Nullable<System.DateTime> datedec { get; set; }
        public int id { get; set; }
    }
}
