//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_sanction
    {
        public Nullable<int> Matricule_ID { get; set; }
        public string Nom_policier { get; set; }
        public string libelle { get; set; }
        public Nullable<System.DateTime> datedec { get; set; }
        public Nullable<int> numdec { get; set; }
        public string motif { get; set; }
        public string Expr1 { get; set; }
        public string autorite { get; set; }
        public int id { get; set; }
    }
}
